# -*- coding: utf-8 -*-
"""Mechanism_synthetic_blending.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDlgsyn09bIDStT10uBnyMn7L0zPDpKL
"""

from sklearn.ensemble import RandomForestClassifier

# ------------------------------------------------------------
# LOAD TRAINING DATA
# ------------------------------------------------------------
X_train = pd.read_csv("X_train.csv", index_col=0)
y_train = pd.read_csv("y_train.csv", index_col=0).iloc[:, 0]

# ------------------------------------------------------------
# REBUILD FINAL RANDOM FOREST MODEL (IDENTICAL PARAMS)
# ------------------------------------------------------------
final_model = RandomForestClassifier(
    n_estimators=800,
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=1,
    max_features="sqrt",
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

final_model.fit(X_train, y_train)

print("Final RandomForest model rebuilt and ready.")

from scipy.stats import entropy
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Helper: recompute FID metrics from a mixed mechanism vector
# ------------------------------------------------------------

def recompute_fid(mixed_mech, arg_idx, vf_idx):
    """
    mixed_mech: 1D numpy array of CLR mechanism values (length 23)
    arg_idx, vf_idx: indices of ARG and VF mechanisms
    """

    # Convert CLR → pseudo-abundance
    abund = np.exp(mixed_mech)
    abund = abund / abund.sum()

    # Split ARG / VF
    abund_arg = abund[arg_idx]
    abund_vf  = abund[vf_idx]

    # Shannon entropies
    H_ARG = entropy(abund_arg, base=2) if abund_arg.sum() > 0 else 0
    H_VF  = entropy(abund_vf,  base=2) if abund_vf.sum() > 0 else 0
    H_TOT = entropy(abund, base=2)

    # Evenness
    J_ARG = H_ARG / np.log2(len(abund_arg)) if len(abund_arg) > 1 else 0
    J_VF  = H_VF  / np.log2(len(abund_vf))  if len(abund_vf)  > 1 else 0

    # Coupling
    FCR = np.log2((H_ARG + 1e-6) / (H_VF + 1e-6))
    Integration_Index = (H_TOT - abs(H_ARG - H_VF)) / H_TOT if H_TOT > 0 else 0

    return [H_ARG, H_VF, H_TOT, J_ARG, J_VF, FCR, Integration_Index]


# ------------------------------------------------------------
# Identify ARG / VF indices ONCE
# ------------------------------------------------------------

arg_mechs = [
    "Antibiotic efflux","Antibiotic inactivation",
    "TargetAlt","TargetRepl","TargetProtect","RedPerm"
]

vf_mechs = [m for m in mechanism_features if m not in arg_mechs]

arg_idx = [i for i, m in enumerate(mechanism_features) if m in arg_mechs]
vf_idx  = [i for i, m in enumerate(mechanism_features) if m in vf_mechs]


# ------------------------------------------------------------
# SYNTHETIC MIXING (FIXED)
# ------------------------------------------------------------

results = []

for donor in envs:
    for recipient in envs:
        if donor == recipient:
            continue

        donor_vec = env_centroids.loc[donor].values
        recipient_vec = env_centroids.loc[recipient].values

        for alpha in alphas:
            mixed_mech = (1 - alpha) * recipient_vec + alpha * donor_vec

            # Recompute FID
            fid_vals = recompute_fid(mixed_mech, arg_idx, vf_idx)

            # Build FULL feature vector (23 + 7 = 30)
            full_vec = np.concatenate([mixed_mech, fid_vals])
            full_df = pd.DataFrame([full_vec], columns=X.columns)

            # Predict
            proba = final_model.predict_proba(full_df)[0]
            pred_class = final_model.classes_[np.argmax(proba)]
            confidence = np.max(proba)
            ent = entropy(proba, base=2)

            results.append({
                "Donor": donor,
                "Recipient": recipient,
                "Alpha_donor": alpha,
                "Predicted": pred_class,
                "Confidence": confidence,
                "Entropy": ent
            })

blend_df = pd.DataFrame(results)
blend_df.to_csv("Synthetic_Mechanism_Mixing_Results.csv", index=False)

print(" Mechanism-level synthetic mixing + FID recomputation complete.")

import pandas as pd

df = pd.read_csv("Synthetic_Mechanism_Mixing_Results.csv")

# 1. Check endpoints behave correctly
print(df[df["Alpha_donor"] == 0].groupby(["Recipient", "Predicted"]).size())
print(df[df["Alpha_donor"] == 1].groupby(["Donor", "Predicted"]).size())

# 2. Check that predictions change with alpha
df.groupby(["Donor", "Recipient", "Alpha_donor"])["Predicted"].nunique().head()

# 3. Quick look at confidence trend
df.groupby("Alpha_donor")["Confidence"].mean()

import pandas as pd

# ------------------------------------------------------------
# LOAD SYNTHETIC MIXING RESULTS
# ------------------------------------------------------------
df = pd.read_csv("Synthetic_Mechanism_Mixing_Results.csv")

# Ensure proper sorting
df = df.sort_values(["Donor", "Recipient", "Alpha_donor"])

switch_points = []

for (donor, recipient), sub in df.groupby(["Donor", "Recipient"]):
    preds = sub["Predicted"].values
    alphas = sub["Alpha_donor"].values

    # Expected initial class
    initial = recipient

    for i in range(1, len(preds)):
        if preds[i] != initial:
            switch_points.append({
                "Donor": donor,
                "Recipient": recipient,
                "Switch_From": initial,
                "Switch_To": preds[i],
                "Alpha_donor": alphas[i],
                "Alpha_recipient": 1 - alphas[i]
            })
            break  # FIRST switch only

switch_df = pd.DataFrame(switch_points)

# Save
switch_df.to_csv(
    "Synthetic_Mechanism_Switch_Points.csv",
    index=False
)

print(" Switch points extracted.")
print(switch_df)

# ------------------------------------------------------------
# SANITY CHECK
# ------------------------------------------------------------

# Sort for readability
switch_df = switch_df.sort_values(
    ["Recipient", "Donor", "Alpha_donor"]
).reset_index(drop=True)

# Save a clean version
switch_df.to_csv(
    "Synthetic_Mechanism_Switch_Table_FINAL.csv",
    index=False
)

print("Final switch table saved.")

import numpy as np

# ------------------------------------------------------------
# BUILD DOMINANCE MATRIX
# ------------------------------------------------------------

envs = sorted(
    set(switch_df["Donor"]) | set(switch_df["Recipient"])
)

dominance = pd.DataFrame(
    0,
    index=envs,
    columns=envs,
    dtype=int
)

for _, row in switch_df.iterrows():
    winner = row["Switch_To"]
    loser = row["Switch_From"]

    if winner in dominance.index and loser in dominance.columns:
        dominance.loc[winner, loser] += 1

# Save matrix
dominance.to_csv(
    "Synthetic_Mechanism_Dominance_Matrix.csv"
)

print(" Dominance matrix computed.")
print(dominance)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load switch table
switch_df = pd.read_csv("Synthetic_Mechanism_Switch_Points.csv")

# Build matrix
switch_mat = switch_df.pivot(
    index="Donor",
    columns="Recipient",
    values="Alpha_donor"
)

plt.figure(figsize=(4.5, 4))
sns.set_theme(style="white")

ax = sns.heatmap(
    switch_mat,
    cmap="vlag_r",
    vmin=0, vmax=1,
    annot=True,
    fmt=".2f",
    linewidths=0.6,
    linecolor="black",
    cbar_kws={"label": "Switch threshold (α donor)"}
)

ax.set_xlabel("Recipient environment", fontsize=10, weight="bold")
ax.set_ylabel("Donor environment", fontsize=10, weight="bold")

plt.tight_layout()
plt.savefig("Switch_Threshold_Heatmap.tiff", dpi=600, bbox_inches="tight")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

dom = pd.read_csv("Synthetic_Mechanism_Dominance_Matrix.csv", index_col=0)

plt.figure(figsize=(4, 3.5))
sns.set_theme(style="white")

ax = sns.heatmap(
    dom,
    cmap="YlGnBu",
    annot=True,
    fmt="d",
    linewidths=0.6,
    linecolor="black",
    cbar_kws={"label": "Number of transition events"}
)

ax.set_xlabel("Recipient environment", fontsize=10, weight="bold")
ax.set_ylabel("Transition-associated environment", fontsize=10, weight="bold")

plt.tight_layout()
plt.savefig("Dominance_Heatmap.tiff", dpi=600, bbox_inches="tight")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import math

# Load synthetic mixing results
df = pd.read_csv("Synthetic_Mechanism_Mixing_Results.csv")

sns.set_theme(style="white")

pairs = df[["Donor", "Recipient"]].drop_duplicates()
n_pairs = len(pairs)

cols = 3
rows = math.ceil(n_pairs / cols)

fig, axes = plt.subplots(rows, cols, figsize=(cols * 5, rows * 4), squeeze=False)

for i, ((donor, recipient), sub) in enumerate(df.groupby(["Donor", "Recipient"])):
    r, c = divmod(i, cols)
    ax = axes[r][c]

    sns.lineplot(
        data=sub,
        x="Alpha_donor",
        y="Confidence",
        hue="Predicted",
        estimator="mean",
        errorbar="sd",
        marker="o",
        linewidth=2,
        ax=ax
    )

    ax.axvline(0.5, linestyle="--", color="grey", linewidth=1)
    ax.set_ylim(0, 1.05)

    ax.set_title(f"{donor} → {recipient}", fontsize=12, weight="bold")
    ax.set_xlabel(f"Fraction of {donor}", fontsize=10)
    ax.set_ylabel("Prediction confidence", fontsize=10)

    ax.legend(fontsize=8, title=None)

# Remove empty panels
for j in range(i + 1, rows * cols):
    fig.delaxes(axes[j // cols][j % cols])

plt.tight_layout()
plt.savefig(
    "Mechanism_Synthetic_Mixing_Confidence_Curves.tiff",
    dpi=600,
    bbox_inches="tight"
)
plt.show()

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import math

# Load synthetic mixing results
df = pd.read_csv("Synthetic_Mechanism_Mixing_Results.csv")

sns.set_theme(style="white")

pairs = df[["Donor", "Recipient"]].drop_duplicates()
n_pairs = len(pairs)

cols = 3
rows = math.ceil(n_pairs / cols)

max_entropy = np.log2(df["Predicted"].nunique())

fig, axes = plt.subplots(rows, cols, figsize=(cols * 5, rows * 4), squeeze=False)

for i, ((donor, recipient), sub) in enumerate(df.groupby(["Donor", "Recipient"])):
    r, c = divmod(i, cols)
    ax = axes[r][c]

    summary = (
        sub
        .groupby("Alpha_donor")["Entropy"]
        .agg(["mean", "std"])
        .reset_index()
    )

    ax.plot(
        summary["Alpha_donor"],
        summary["mean"],
        marker="o",
        linewidth=2
    )

    ax.fill_between(
        summary["Alpha_donor"],
        summary["mean"] - summary["std"],
        summary["mean"] + summary["std"],
        alpha=0.25
    )

    ax.axhline(max_entropy, linestyle="--", color="red", linewidth=1)
    ax.axvline(0.5, linestyle="--", color="grey", linewidth=1)

    ax.set_title(f"{donor} → {recipient}", fontsize=12, weight="bold")
    ax.set_xlabel(f"Fraction of {donor}", fontsize=10)
    ax.set_ylabel("Prediction entropy", fontsize=10)

    ax.set_ylim(0, max_entropy + 0.2)

# Remove empty panels
for j in range(i + 1, rows * cols):
    fig.delaxes(axes[j // cols][j % cols])

plt.tight_layout()
plt.savefig(
    "Mechanism_Synthetic_Mixing_Entropy_Curves.tiff",
    dpi=600,
    bbox_inches="tight"
)
plt.show()
