# -*- coding: utf-8 -*-
"""PAPER2_mACHINE_lEARNING_FUNCTIONAL ARG_VF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xW1tFM-8as7KXF7gROh-7g5BN3mCbAzr
"""

import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. LOAD DATA (CORRECT DELIMITERS)
# ------------------------------------------------------------

# Mechanism-level CLR matrix (samples × 23 mechanisms)
mech = pd.read_csv(
    "Mechanism_CLR_batch_corrected_v1.tsv",
    sep=",",
    index_col=0
)

# Functional Integration Diversity table
fid = pd.read_csv(
    "Functional_Integration_Diversity_Table_v4.csv"
)

# ------------------------------------------------------------
# 2. CLEAN & ALIGN SAMPLE IDS
# ------------------------------------------------------------

fid["Sample_ID"] = fid["Sample_ID"].astype(str).str.strip()
mech.index = mech.index.astype(str).str.strip()

print("Samples in mechanism CLR:", mech.shape[0])
print("Samples in FID table:", fid.shape[0])

# Keep only common samples
common_ids = mech.index.intersection(fid["Sample_ID"])
print(" Common samples retained:", len(common_ids))

if len(common_ids) == 0:
    raise ValueError(" No overlapping Sample_IDs — check naming upstream.")

mech = mech.loc[common_ids].sort_index()
fid  = fid.set_index("Sample_ID").loc[common_ids].sort_index()

# ------------------------------------------------------------
# 3. SELECT FEATURES
# ------------------------------------------------------------

# Mechanism CLR features (23 mechanisms)
X_mech = mech.copy()

# FID-derived features
fid_features = [
    "H_ARG",
    "H_VF",
    "H_TOT",
    "J_ARG",
    "J_VF",
    "FCR",
    "Integration_Index"
]

X_fid = fid[fid_features]

# ------------------------------------------------------------
# 4. COMBINE FEATURE BLOCKS
# ------------------------------------------------------------

X = pd.concat([X_mech, X_fid], axis=1)

# Target label
y = fid["Group"]

# ------------------------------------------------------------
# 5. SANITY CHECKS
# ------------------------------------------------------------

print("\n--- SANITY CHECKS ---")
print("X shape:", X.shape)
print("y shape:", y.shape)
print("Missing values in X:", X.isna().sum().sum())
print("Classes:", y.value_counts())

assert "Group" not in X.columns
assert X.shape[0] == y.shape[0]

# ------------------------------------------------------------
# 6. SAVE FINAL ML MATRICES
# ------------------------------------------------------------

X.to_csv("ML_Features.csv")
y.to_csv("ML_Labels.csv", header=True)

print("\n FINAL ML MATRIX READY")
print("Files written:")
print(" - ML_Features.csv")
print(" - ML_Labels.csv")

# ============================================================
# ML BENCHMARKING SETUP — STRATIFIED 80/20 HOLDOUT
# ============================================================

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# ------------------------------------------------------------
# 1. LOAD FINAL ML MATRICES
# ------------------------------------------------------------

X = pd.read_csv(
    "ML_Features.csv",
    index_col=0
)

y = pd.read_csv(
    "ML_Labels.csv",
    index_col=0
).iloc[:, 0]

print("X shape:", X.shape)
print("y shape:", y.shape)
print("\nClass distribution:")
print(y.value_counts())

# ------------------------------------------------------------
# 2. STRATIFIED 80/20 SPLIT
# ------------------------------------------------------------

X_train, X_holdout, y_train, y_holdout = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\n--- SPLIT SUMMARY ---")
print("Training samples:", X_train.shape[0])
print("Holdout samples :", X_holdout.shape[0])

print("\nTraining class distribution:")
print(y_train.value_counts())

print("\nHoldout class distribution:")
print(y_holdout.value_counts())


# ------------------------------------------------------------
# 3. SAVE SPLITS (IMPORTANT)
# ------------------------------------------------------------

X_train.to_csv("X_train.csv")
X_holdout.to_csv("X_holdout.csv")

y_train.to_csv("y_train.csv", header=True)
y_holdout.to_csv("y_holdout.csv", header=True)

print("\n 80/20 stratified holdout split completed and saved.")

# ============================================================
# ML BENCHMARKING — MULTI-MODEL COMPARISON
# Training set only (80%)
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import RepeatedStratifiedKFold, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

# ------------------------------------------------------------
# 1. LOAD TRAINING DATA ONLY
# ------------------------------------------------------------

X_train = pd.read_csv("X_train.csv", index_col=0)
y_train = pd.read_csv("y_train.csv", index_col=0).iloc[:, 0]

# ------------------------------------------------------------
# 2. CV STRATEGY
# ------------------------------------------------------------

cv = RepeatedStratifiedKFold(
    n_splits=5,
    n_repeats=3,
    random_state=42
)

scoring = {
    "balanced_accuracy": "balanced_accuracy",
    "macro_f1": "f1_macro",
    "macro_recall": "recall_macro",
    "mcc": "matthews_corrcoef"
}

# ------------------------------------------------------------
# 3. MODELS
# ------------------------------------------------------------

models = {
    "DecisionTree": DecisionTreeClassifier(
        random_state=42
    ),

    "RandomForest": RandomForestClassifier(
        n_estimators=500,
        max_features="sqrt",
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ),

    "LogisticRegression": Pipeline([
        ("scaler", StandardScaler()),
        ("clf", LogisticRegression(
            penalty="elasticnet",
            solver="saga",
            l1_ratio=0.5,
            max_iter=5000,
            class_weight="balanced",
            random_state=42
        ))
    ]),

    "SVM": Pipeline([
        ("scaler", StandardScaler()),
        ("clf", SVC(
            kernel="rbf",
            C=1.0,
            gamma="scale",
            class_weight="balanced",
            random_state=42
        ))
    ]),

    "GradientBoosting": GradientBoostingClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=3,
        random_state=42
    )
}

# ------------------------------------------------------------
# 4. BENCHMARKING
# ------------------------------------------------------------

results = []

for name, model in models.items():
    print(f"\n🔹 Benchmarking {name}...")

    cv_results = cross_validate(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring=scoring,
        n_jobs=-1,
        return_train_score=False
    )

    results.append({
        "Model": name,
        "BalancedAccuracy_mean": np.mean(cv_results["test_balanced_accuracy"]),
        "BalancedAccuracy_std": np.std(cv_results["test_balanced_accuracy"]),
        "MacroF1_mean": np.mean(cv_results["test_macro_f1"]),
        "MacroF1_std": np.std(cv_results["test_macro_f1"]),
        "MacroRecall_mean": np.mean(cv_results["test_macro_recall"]),
        "MacroRecall_std": np.std(cv_results["test_macro_recall"]),
        "MCC_mean": np.mean(cv_results["test_mcc"]),
        "MCC_std": np.std(cv_results["test_mcc"])
    })

# ------------------------------------------------------------
# 5. RESULTS TABLE
# ------------------------------------------------------------

results_df = pd.DataFrame(results).sort_values(
    by="MCC_mean",
    ascending=False
)

print("\n=== BENCHMARK RESULTS (TRAINING SET CV) ===")
print(results_df)

results_df.to_csv(
    "ML_Model_Benchmarking_TrainingCV_RobustMetrics.csv",
    index=False
)

print("\n Robust benchmarking completed and saved.")

import numpy as np
import pandas as pd
from scipy.stats import wilcoxon

from sklearn.model_selection import RepeatedStratifiedKFold, cross_validate
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

# Load training data
X_train = pd.read_csv("X_train.csv", index_col=0)
y_train = pd.read_csv("y_train.csv", index_col=0).iloc[:, 0]

cv = RepeatedStratifiedKFold(
    n_splits=5,
    n_repeats=3,
    random_state=42
)

scoring = {"mcc": "matthews_corrcoef"}

# Models
rf = RandomForestClassifier(
    n_estimators=500,
    max_features="sqrt",
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

svm = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", SVC(
        kernel="rbf",
        C=1.0,
        gamma="scale",
        class_weight="balanced",
        random_state=42
    ))
])

# CV MCC scores
rf_scores = cross_validate(
    rf, X_train, y_train, cv=cv, scoring=scoring
)["test_mcc"]

svm_scores = cross_validate(
    svm, X_train, y_train, cv=cv, scoring=scoring
)["test_mcc"]

# Wilcoxon signed-rank test
stat, p = wilcoxon(rf_scores, svm_scores)

print("RF MCC mean ± SD:", np.mean(rf_scores), np.std(rf_scores))
print("SVM MCC mean ± SD:", np.mean(svm_scores), np.std(svm_scores))
print("Wilcoxon p-value (RF vs SVM):", p)

model_colors = {
    "RandomForest":       "#1f78b4",  # blue (ensemble, primary)
    "SVM":                "#33a02c",  # green
    "GradientBoosting":   "#ff7f00",  # orange
    "LogisticRegression": "#6a3d9a",  # purple
    "DecisionTree":       "#b15928"   # brown (baseline)
}

import matplotlib.pyplot as plt

# Sort models by performance
plot_df = results_df.sort_values("MCC_mean")

fig, ax = plt.subplots(figsize=(4.5, 3.2))

y_pos = range(len(plot_df))

# Plot error bars (black, neutral)
ax.errorbar(
    plot_df["MCC_mean"],
    y_pos,
    xerr=plot_df["MCC_std"],
    fmt="none",
    ecolor="black",
    elinewidth=1.2,
    capsize=4,
    capthick=1.2,
    zorder=1
)

# Plot colored points
ax.scatter(
    plot_df["MCC_mean"],
    y_pos,
    s=90,
    c=[model_colors[m] for m in plot_df["Model"]],
    edgecolor="black",
    linewidth=0.6,
    zorder=2
)

# Y axis labels
ax.set_yticks(y_pos)
ax.set_yticklabels(plot_df["Model"], fontsize=11)

# X axis
ax.set_xlabel(
    "Matthews Correlation Coefficient (MCC)",
    fontsize=8,
    fontweight="bold"
)

# Title (short, journal style)
ax.set_title(
    "",
    fontsize=13,
    fontweight="bold",
    pad=8
)

# Clean aesthetics
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.spines["left"].set_linewidth(1.5)
ax.spines["bottom"].set_linewidth(1.5)

ax.tick_params(axis="x", labelsize=10)
ax.tick_params(axis="y", length=0)

plt.tight_layout()

plt.savefig(
    "Figure_ML_Benchmarking_MCC.tiff",
    dpi=600,
    bbox_inches="tight"
)

plt.show()

# ============================================================
# RandomForest Nested CV + Holdout Evaluation
# ============================================================

import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.metrics import (
    matthews_corrcoef,
    balanced_accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# ------------------------------------------------------------
# 1. LOAD TRAIN / HOLDOUT DATA (CORRECT FILES)
# ------------------------------------------------------------

X_train = pd.read_csv("X_train.csv", index_col=0)
X_holdout = pd.read_csv("X_holdout.csv", index_col=0)

y_train = pd.read_csv("y_train.csv", index_col=0).iloc[:, 0]
y_holdout = pd.read_csv("y_holdout.csv", index_col=0).iloc[:, 0]

print("Training set:", X_train.shape)
print("Holdout set :", X_holdout.shape)

# ------------------------------------------------------------
# 2. DEFINE MODEL + PARAMETER GRID
# ------------------------------------------------------------

rf = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

param_grid = {
    "n_estimators": [300, 500, 800],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 5],
    "max_features": ["sqrt", "log2"],
    "class_weight": ["balanced"]
}

# ------------------------------------------------------------
# 3. NESTED CROSS-VALIDATION (TRAINING SET ONLY)
# ------------------------------------------------------------

outer_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
inner_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

outer_results = []

print("\n Starting nested cross-validation...")

for fold, (tr_idx, te_idx) in enumerate(outer_cv.split(X_train, y_train), 1):

    X_tr, X_te = X_train.iloc[tr_idx], X_train.iloc[te_idx]
    y_tr, y_te = y_train.iloc[tr_idx], y_train.iloc[te_idx]

    grid = GridSearchCV(
        estimator=rf,
        param_grid=param_grid,
        scoring="balanced_accuracy",
        cv=inner_cv,
        n_jobs=-1,
        refit=True
    )

    grid.fit(X_tr, y_tr)
    best_model = grid.best_estimator_

    y_pred = best_model.predict(X_te)

    outer_results.append({
        "Fold": fold,
        "MCC": matthews_corrcoef(y_te, y_pred),
        "BalancedAccuracy": balanced_accuracy_score(y_te, y_pred),
        "MacroF1": f1_score(y_te, y_pred, average="macro")
    })

    print(f"  Fold {fold} done.")

cv_results = pd.DataFrame(outer_results)

cv_results.to_csv(
    "RF_NestedCV_Training_Performance.csv",
    index=False
)

print("\n=== NESTED CV PERFORMANCE (TRAINING) ===")
print(cv_results.describe())

# ------------------------------------------------------------
# 4. TRAIN FINAL MODEL ON FULL TRAINING SET
# ------------------------------------------------------------

print("\n Training final model on full training set...")

final_grid = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    scoring="balanced_accuracy",
    cv=inner_cv,
    n_jobs=-1,
    refit=True
)

final_grid.fit(X_train, y_train)
final_model = final_grid.best_estimator_

print("Best parameters:")
print(final_grid.best_params_)

# ------------------------------------------------------------
# 5. FINAL HOLDOUT EVALUATION (ONCE)
# ------------------------------------------------------------

print("\n Evaluating on holdout set...")

y_holdout_pred = final_model.predict(X_holdout)

holdout_metrics = {
    "MCC": matthews_corrcoef(y_holdout, y_holdout_pred),
    "BalancedAccuracy": balanced_accuracy_score(y_holdout, y_holdout_pred),
    "MacroF1": f1_score(y_holdout, y_holdout_pred, average="macro")
}

holdout_df = pd.DataFrame([holdout_metrics])
holdout_df.to_csv(
    "RF_Final_Holdout_Performance.csv",
    index=False
)

print("\n=== FINAL HOLDOUT PERFORMANCE ===")
print(holdout_df)

# Confusion matrix
cm = confusion_matrix(
    y_holdout,
    y_holdout_pred,
    labels=final_model.classes_
)

cm_df = pd.DataFrame(
    cm,
    index=final_model.classes_,
    columns=final_model.classes_
)

cm_df.to_csv("RF_Holdout_Confusion_Matrix.csv")

print("\nClassification report:")
print(classification_report(y_holdout, y_holdout_pred))

print("\n RandomForest nested CV + holdout evaluation COMPLETE.")

# ============================================================
# FEATURE IMPORTANCE (CONSENSUS ANALYSIS)
# RandomForest + Gini + Permutation (HOLDOUT)
# ============================================================

import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.inspection import permutation_importance
from sklearn.metrics import matthews_corrcoef, balanced_accuracy_score

# ------------------------------------------------------------
# 1. LOAD FINAL DATA SPLITS
# ------------------------------------------------------------

X_train = pd.read_csv("X_train.csv", index_col=0)
X_hold  = pd.read_csv("X_holdout.csv", index_col=0)

y_train = pd.read_csv("y_train.csv", index_col=0).iloc[:, 0]
y_hold  = pd.read_csv("y_holdout.csv", index_col=0).iloc[:, 0]

print("Training set:", X_train.shape)
print("Holdout set :", X_hold.shape)

# ------------------------------------------------------------
# 2. TRAIN FINAL RANDOM FOREST (BEST PARAMS)
# ------------------------------------------------------------

rf_final = RandomForestClassifier(
    n_estimators=800,
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=1,
    max_features="sqrt",
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_final.fit(X_train, y_train)

# ------------------------------------------------------------
# 3. GINI IMPORTANCE
# ------------------------------------------------------------

gini_imp = pd.DataFrame({
    "Feature": X_train.columns,
    "Gini_importance": rf_final.feature_importances_
}).sort_values(
    "Gini_importance", ascending=False
).reset_index(drop=True)

gini_imp["Gini_rank"] = gini_imp.index + 1

# ------------------------------------------------------------
# 4. PERMUTATION IMPORTANCE (HOLDOUT ONLY)
# ------------------------------------------------------------

perm = permutation_importance(
    rf_final,
    X_hold,
    y_hold,
    scoring="balanced_accuracy",
    n_repeats=50,
    random_state=42,
    n_jobs=-1
)

perm_imp = pd.DataFrame({
    "Feature": X_train.columns,
    "Permutation_mean": perm.importances_mean,
    "Permutation_std": perm.importances_std
}).sort_values(
    "Permutation_mean", ascending=False
).reset_index(drop=True)

perm_imp["Permutation_rank"] = perm_imp.index + 1

# ------------------------------------------------------------
# 5. MERGE + CONSENSUS FEATURES
# ------------------------------------------------------------

importance = (
    gini_imp
    .merge(perm_imp, on="Feature")
)

# Define consensus threshold
TOP_N = 20

importance["Consensus"] = (
    (importance["Gini_rank"] <= TOP_N) &
    (importance["Permutation_rank"] <= TOP_N)
)
# ------------------------------------------------------------
# 6. SAVE OUTPUTS
# ------------------------------------------------------------

importance.to_csv(
    "ML_Feature_Importance_Gini_Permutation.csv",
    index=False
)

consensus = importance[importance["Consensus"]].copy()

consensus.to_csv(
    "ML_Feature_Consensus_TOP20.csv",
    index=False
)

print("\n FEATURE IMPORTANCE COMPLETE")
print("Saved:")
print(" - ML_Feature_Importance_Gini_Permutation.csv")
print(" - ML_Feature_Consensus_TOP20.csv")

print("\nConsensus features:")
print(consensus[[
    "Feature",
    "Gini_rank",
    "Permutation_rank"
]])

# ============================================================
#  Feature Importance Figure
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# 1. LOAD FEATURE IMPORTANCE TABLE
# ------------------------------------------------------------

imp = pd.read_csv("ML_Feature_Importance_Gini_Permutation.csv")

# Keep only consensus features
consensus = imp[imp["Consensus"]].copy()

# ------------------------------------------------------------
# 2. APPLY CANONICAL MECHANISM RENAMING
# ------------------------------------------------------------

mechanism_short_labels = {
    "Adherence": "Adherence",
    "antibiotic efflux": "Antibiotic efflux",
    "antibiotic efflux;antibiotic target alteration": "Efflux + TargetAlt",
    "antibiotic efflux;reduced permeability to antibiotic": "Efflux + RedPerm",
    "antibiotic inactivation": "Antibiotic inactivation",
    "antibiotic inactivation;antibiotic target alteration": "Inact + TargetAlt",
    "antibiotic target alteration": "TargetAlt",
    "antibiotic target alteration;antibiotic target replacement": "TargetAlt + TargetRepl",
    "antibiotic target protection": "TargetProtect",
    "antibiotic target replacement": "TargetRepl",
    "Antimicrobial activity Competitive advantage": "CompetitiveAdv",
    "Biofilm": "Biofilm",
    "Effector delivery system": "Effector delivery system",
    "Exoenzyme": "Exoenzyme",
    "Exotoxin": "Exotoxin",
    "Immune modulation": "Immune modulation",
    "Invasion": "Invasion",
    "Motility": "Motility",
    "Nutritional Metabolic factor": "Nutritional Metabolic factor",
    "Others": "Others",
    "reduced permeability to antibiotic": "RedPerm",
    "Regulation": "Regulation",
    "Stress survival": "Stress survival"
}

consensus["Feature_short"] = consensus["Feature"].map(mechanism_short_labels)

# Drop any unmapped features (safety)
consensus = consensus.dropna(subset=["Feature_short"])

# ------------------------------------------------------------
# 3. DEFINE FEATURE CLASSES (UNCHANGED)
# ------------------------------------------------------------

virulence = {
    "Exotoxin",
    "Effector delivery system",
    "Biofilm",
    "Motility",
    "Exoenzyme",
    "Invasion"
}

resistance = {
    "RedPerm",
    "TargetAlt",
    "TargetRepl",
    "TargetProtect",
    "Antibiotic inactivation"
}

def classify_feature(f):
    if f in virulence:
        return "Virulence"
    elif f in resistance:
        return "Resistance"
    else:
        return "Integration"

consensus["Class"] = consensus["Feature_short"].apply(classify_feature)

# ------------------------------------------------------------
# 4. SORT BY PERMUTATION IMPORTANCE
# ------------------------------------------------------------

consensus = consensus.sort_values(
    "Permutation_mean",
    ascending=True
)

# ------------------------------------------------------------
# 5. COLOR PALETTE (CONSISTENT WITH PAPER)
# ------------------------------------------------------------

colors = {
    "Virulence":   "#B2182B",
    "Resistance":  "#2166AC",
    "Integration": "#4D4D4D"
}

# ------------------------------------------------------------
# 6. PLOT
# ------------------------------------------------------------

fig, ax = plt.subplots(figsize=(5.2, 4.0))

y_pos = range(len(consensus))

# Error bars
ax.errorbar(
    consensus["Permutation_mean"],
    y_pos,
    xerr=consensus["Permutation_std"],
    fmt="none",
    ecolor="black",
    elinewidth=1.1,
    capsize=3,
    zorder=1
)

# Points
ax.scatter(
    consensus["Permutation_mean"],
    y_pos,
    c=[colors[c] for c in consensus["Class"]],
    s=85,
    edgecolor="black",
    linewidth=0.6,
    zorder=2
)

# Y labels
ax.set_yticks(y_pos)
ax.set_yticklabels(consensus["Feature_short"], fontsize=10)

# X label
ax.set_xlabel(
    "Permutation importance (Δ balanced accuracy)",
    fontsize=8,
    fontweight="bold"
)

# Clean axes
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.spines["left"].set_linewidth(1.4)
ax.spines["bottom"].set_linewidth(1.4)

ax.tick_params(axis="x", labelsize=10)
ax.tick_params(axis="y", length=0)

# Legend
for cls, col in colors.items():
    ax.scatter([], [], c=col, label=cls, s=80, edgecolor="black")

ax.legend(
    frameon=False,
    fontsize=9,
    loc="lower right"
)

plt.tight_layout()

plt.savefig(
    "Figure_Feature_Importance_Consensus.tiff",
    dpi=600,
    bbox_inches="tight"
)

plt.show()
