# -*- coding: utf-8 -*-
"""ARG_VFDB_Genome_Resolved.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gp9yE3R1N8u9A-K12NM3yrfe7b4FSsNz
"""

# ==========================================================
#  LOAD DATA
# ==========================================================
import pandas as pd
import re

arg = pd.read_csv("arg_with_species.tsv", sep="\t")
vf = pd.read_csv("vfdb_with_species.tsv", sep="\t")
meta = pd.read_csv("Merged_metadata_all.csv")

# ==========================================================
#  CLEANING FUNCTIONS
# ==========================================================
def clean_taxonomy(tax):
    """Normalize separators and underscores in taxonomy strings."""
    if pd.isna(tax):
        return None
    tax = re.sub(r'__+', '_', tax)
    tax = tax.replace(';_', ';')
    tax = tax.strip(';_ ')
    return tax

def extract_species_name(tax):
    """Hierarchical fallback: species > genus spp. > family > Unclassified."""
    if pd.isna(tax):
        return "Unclassified"
    # Capture full species names with underscores/spaces/hyphens
    species_match = re.search(r's_([\w\s\.\-\(\)]+)$', tax)
    genus_match = re.search(r'g_([\w\s\.\-\(\)]+)', tax)
    family_match = re.search(r'f_([\w\s\.\-\(\)]+)', tax)
    if species_match and species_match.group(1).strip():
        return species_match.group(1).strip()
    elif genus_match and genus_match.group(1).strip():
        return f"{genus_match.group(1).strip()} spp."
    elif family_match and family_match.group(1).strip():
        return family_match.group(1).strip()
    else:
        return "Unclassified"

# ==========================================================
#  ARG CLEANING
# ==========================================================
arg['Gene_name'] = arg['Gene'].str.extract(r'gene=([^|]+)')
arg['Gene_name'] = arg['Gene_name'].str.strip()

arg['Genome'] = arg['Gene'].str.extract(r'sample=([\w\-\.\_]+)')
arg['Genome'] = arg['Genome'].str.strip()

arg['Species'] = arg['Species'].apply(clean_taxonomy)
arg['Species_name'] = arg['Species'].apply(extract_species_name)

# ==========================================================
# VFDB CLEANING
# ==========================================================
vf['Gene_name'] = vf['Gene'].str.extract(r'gene=([^|]+)')
vf['Gene_name'] = vf['Gene_name'].str.strip()

vf['Genome'] = vf['Gene'].str.extract(r'^([^|]+)')
vf['Genome'] = vf['Genome'].str.strip()

vf['Species'] = vf['Species'].apply(clean_taxonomy)
vf['Species_name'] = vf['Species'].apply(extract_species_name)

# ==========================================================
# STANDARDIZE COLUMNS
# ==========================================================
arg.rename(columns={'Read Count': 'Read_Count'}, inplace=True, errors='ignore')
vf.rename(columns={'Read count': 'Read_Count'}, inplace=True, errors='ignore')

cols = ['Sample_ID', 'Genome', 'Gene_name', 'TPM', 'Read_Count', 'Species', 'Species_name']
arg = arg[cols].copy()
vf = vf[cols].copy()

arg.dropna(subset=['Genome', 'Gene_name'], inplace=True)
vf.dropna(subset=['Genome', 'Gene_name'], inplace=True)

arg.drop_duplicates(inplace=True)
vf.drop_duplicates(inplace=True)

# ==========================================================
#  FIND DUAL-POSITIVE GENOMES IF THEY EXIST
# ==========================================================
shared_genomes = set(arg['Genome']).intersection(set(vf['Genome']))
print(f" Shared genomes with both ARG and VF hits: {len(shared_genomes)}")

arg_dual = arg[arg['Genome'].isin(shared_genomes)]
vf_dual = vf[vf['Genome'].isin(shared_genomes)]

# ==========================================================
# MERGE WITH METADATA
# ==========================================================
# Ensure consistent column names
meta.columns = meta.columns.str.strip()
meta = meta.rename(columns=lambda x: x.replace(" ", "_"))

# Try to merge based on Sample_ID or Genome if applicable
merged_arg = arg_dual.merge(meta, how='left', left_on='Sample_ID', right_on='Sample_ID')
merged_vf = vf_dual.merge(meta, how='left', left_on='Sample_ID', right_on='Sample_ID')

# Add an indicator for data source
merged_arg['Data_source'] = 'ARG'
merged_vf['Data_source'] = 'VF'

# Combine into one unified dataframe
combined = pd.concat([merged_arg, merged_vf], ignore_index=True)

# ==========================================================
# SAVE CLEAN FILES
# ==========================================================
arg.to_csv("ARG_clean.tsv", sep="\t", index=False)
vf.to_csv("VF_clean.tsv", sep="\t", index=False)
arg_dual.to_csv("ARG_dual_positive.tsv", sep="\t", index=False)
vf_dual.to_csv("VF_dual_positive.tsv", sep="\t", index=False)
combined.to_csv("Unified_ARG_VF_Metadata.tsv", sep="\t", index=False)

# ==========================================================
# SUMMARY OUTPUT
# ==========================================================
print("\n Cleaning + Metadata Integration complete!")
print(f"ARG_clean: {len(arg)} rows")
print(f"VF_clean: {len(vf)} rows")
print(f"Dual-positive genomes: {len(shared_genomes)}")
print(f"Unified dataset: {len(combined)} rows")
print(f"Columns in unified dataset: {list(combined.columns)}")

import pandas as pd
import re

# ==========================================================
# LOAD INPUT FILES
# ==========================================================
arg = pd.read_csv("ARG_clean.tsv", sep="\t")
vf = pd.read_csv("VF_clean.tsv", sep="\t")
vf_raw = pd.read_csv("vfdb_with_species.tsv", sep="\t")   # full VF file for mechanism extraction
meta = pd.read_csv("Merged_metadata_all.csv")
aro = pd.read_csv("aro_index.tsv", sep="\t")

# ==========================================================
# CLEANING FUNCTIONS
# ==========================================================
def clean_taxonomy(tax):
    if pd.isna(tax):
        return None
    tax = re.sub(r'__+', '_', tax)
    tax = tax.replace(';_', ';').strip(';_ ')
    return tax

def extract_species_name(tax):
    if pd.isna(tax):
        return "Unclassified"
    species_match = re.search(r's_([\w\s\.\-\(\)]+)$', tax)
    genus_match   = re.search(r'g_([\w\s\.\-\(\)]+)', tax)
    family_match  = re.search(r'f_([\w\s\.\-\(\)]+)', tax)
    if species_match and species_match.group(1).strip():
        return species_match.group(1).strip()
    elif genus_match and genus_match.group(1).strip():
        return f"{genus_match.group(1).strip()} spp."
    elif family_match and family_match.group(1).strip():
        return family_match.group(1).strip()
    else:
        return "Unclassified"

# ==========================================================
# TAXONOMY CLEANUP
# ==========================================================
for df in [arg, vf]:
    df['Species'] = df['Species'].apply(clean_taxonomy)
    df['Species_name'] = df['Species'].apply(extract_species_name)

# ==========================================================
# ARG MECHANISM ANNOTATION (with fuzzy matching)
# ==========================================================
aro.columns = aro.columns.str.strip().str.replace(" ", "_")
aro_subset = aro[['Model_Name', 'AMR_Gene_Family', 'Drug_Class',
                  'Resistance_Mechanism', 'CARD_Short_Name']].copy()

# Step 1: exact match
arg = arg.merge(aro_subset, how="left", left_on="Gene_name", right_on="Model_Name")

# Step 2: fuzzy / partial match for unmapped genes
missing = arg[arg['AMR_Gene_Family'].isna()].copy()
mapped_rows = []

for gene in missing['Gene_name'].unique():
    matches = aro_subset[aro_subset['Model_Name'].str.contains(gene, case=False, regex=False)]
    if not matches.empty:
        m = matches.iloc[0]
        mapped_rows.append({
            'Gene_name': gene,
            'AMR_Gene_Family': m['AMR_Gene_Family'],
            'Drug_Class': m['Drug_Class'],
            'Resistance_Mechanism': m['Resistance_Mechanism'],
            'CARD_Short_Name': m['CARD_Short_Name']
        })

mapped_df = pd.DataFrame(mapped_rows)

if not mapped_df.empty:
    arg = arg.merge(mapped_df, on='Gene_name', how='left', suffixes=('', '_fuzzy'))
    for col in ['AMR_Gene_Family', 'Drug_Class', 'Resistance_Mechanism', 'CARD_Short_Name']:
        fuzzy_col = f"{col}_fuzzy"
        if fuzzy_col in arg.columns:
            arg[col] = arg[col].fillna(arg[fuzzy_col])
            arg.drop(columns=[fuzzy_col], inplace=True, errors='ignore')
else:
    print(" No fuzzy matches needed — all ARG genes matched directly.")

arg.rename(columns={
    "AMR_Gene_Family": "ARG_Gene_Family",
    "Drug_Class": "ARG_Drug_Class",
    "Resistance_Mechanism": "ARG_Mechanism",
    "CARD_Short_Name": "ARG_Short_Name"
}, inplace=True)

arg.fillna("Unknown", inplace=True)
arg['Data_source'] = 'ARG'

# ==========================================================
# VFDB MECHANISM RESTORATION (from raw file)
# ==========================================================
vf_raw['Gene_name'] = vf_raw['Gene'].str.extract(r'gene=([\w\-\(\)]+)')
vf_raw['VF_Mechanism'] = vf_raw['Gene'].str.extract(r'category=([\w\_\-]+)')
vf_raw['VF_Mechanism'] = vf_raw['VF_Mechanism'].str.replace('_', ' ', regex=True)

vf_map = vf_raw[['Gene_name', 'VF_Mechanism']].dropna().drop_duplicates()

vf = vf.merge(vf_map, on='Gene_name', how='left')
vf['VF_Mechanism'] = vf['VF_Mechanism'].fillna('Unknown')
vf['Data_source'] = 'VF'

# ==========================================================
# MERGE WITH METADATA
# ==========================================================
meta.columns = meta.columns.str.strip()
meta = meta.rename(columns=lambda x: x.replace(" ", "_"))

arg_meta = arg.merge(meta, how='left', on='Sample_ID')
vf_meta = vf.merge(meta, how='left', on='Sample_ID')
combined = pd.concat([arg_meta, vf_meta], ignore_index=True)


# ==========================================================
# SAVE INTERMEDIATE
# ==========================================================
arg.to_csv("ARG_mechanism.tsv", sep="\t", index=False)
vf.to_csv("VF_mechanism.tsv", sep="\t", index=False)
combined.to_csv("Unified_ARG_VF_Metadata_Mechanisms.tsv", sep="\t", index=False)


# ==========================================================
#  SUMMARY
# ==========================================================
print(f"ARG annotated: {len(arg)}")
print(f"VF annotated: {len(vf)}")
print(f"Unified rows: {len(combined)}")
print(f"Unique ARG mechanisms: {arg['ARG_Mechanism'].nunique()}")
print(f"Unique VF mechanisms: {vf['VF_Mechanism'].nunique()}")
print("\nSaved:")
print(" • ARG_mechanism.tsv")
print(" • VF_mechanism.tsv")
print(" • Unified_ARG_VF_Metadata_Mechanisms.tsv")

"""##Harmonization of the Data before CLR Transformation"""

# ==========================================================
# Harmonization of ARG & VFDB Mechanism Tables
# ==========================================================
import pandas as pd
import re

# ---------- LOAD CLEANED MECHANISM FILES ----------
arg = pd.read_csv("ARG_mechanism.tsv", sep="\t")
vf  = pd.read_csv("VF_mechanism.tsv", sep="\t")

# ==========================================================
# CLEANUP FUNCTION: REMOVE VFC CODES & EXTRA SPACES
# ==========================================================
def remove_vfc_codes(text):
    """Remove VFDB codes (e.g., 'VFC0271') and extra spaces."""
    if pd.isna(text):
        return text
    text = str(text)
    text = re.sub(r'\bVFC\d+\b', '', text)   # remove codes like VFC0271
    text = re.sub(r'\s+', ' ', text)         # remove multiple spaces
    return text.strip()

# ==========================================================
# HARMONIZE ARG COLUMNS
# ==========================================================

arg_harmonized = arg_meta[[
    "Group",
    "Sample_ID",
    "Data_source",
    "ARG_Short_Name",
    "ARG_Mechanism",
    "TPM",
    "Species_name"
]].rename(columns={
    "ARG_Short_Name": "Gene_ID",
    "ARG_Mechanism": "Mechanisms"
})


# Clean possible stray spaces or characters
arg_harmonized["Gene_ID"] = arg_harmonized["Gene_ID"].apply(remove_vfc_codes)
arg_harmonized["Mechanisms"] = arg_harmonized["Mechanisms"].apply(remove_vfc_codes)

# Order columns
arg_harmonized = arg_harmonized[[
    "Group", "Sample_ID", "Data_source",
    "Gene_ID", "Mechanisms", "TPM", "Species_name"
]]

# ==========================================================
# HARMONIZE VFDB COLUMNS
# ==========================================================
vf_harmonized = vf_meta[[
    "Group",
    "Sample_ID",
    "Data_source",
    "Gene_name",
    "VF_Mechanism",
    "TPM",
    "Species_name"
]].rename(columns={
    "Gene_name": "Gene_ID",
    "VF_Mechanism": "Mechanisms"
})



# Remove VFC codes and spaces
vf_harmonized["Gene_ID"] = vf_harmonized["Gene_ID"].apply(remove_vfc_codes)
vf_harmonized["Mechanisms"] = vf_harmonized["Mechanisms"].apply(remove_vfc_codes)

# Match column order to ARG schema
vf_harmonized = vf_harmonized[[
    "Group", "Sample_ID", "Data_source",
    "Gene_ID", "Mechanisms", "TPM", "Species_name"
]]

# ==========================================================
# MERGE BOTH DATASETS
# ==========================================================
combined_harmonized = pd.concat([arg_harmonized, vf_harmonized], ignore_index=True)

# Drop missing or placeholder mechanisms
combined_harmonized = combined_harmonized[
    combined_harmonized["Mechanisms"].notna() &
    (combined_harmonized["Mechanisms"].str.lower() != "unknown") &
    (combined_harmonized["Mechanisms"].str.lower() != "na")
]

# ==========================================================
# SAVE HARMONIZED FILE
# ==========================================================
combined_harmonized.to_csv("Combined_ARG_VFDB_Harmonized.tsv", sep="\t", index=False)

# ==========================================================
# SUMMARY
# ==========================================================
print("\n ARG & VFDB Harmonization Complete (Final Version)!")
print(f"ARG entries: {len(arg_harmonized)}")
print(f"VF entries: {len(vf_harmonized)}")
print(f"Combined harmonized entries: {len(combined_harmonized)}")
print(f"Unique mechanisms: {combined_harmonized['Mechanisms'].nunique()}")
print("Saved: Combined_ARG_VFDB_Harmonized.tsv")

import pandas as pd

df = pd.read_csv("Combined_ARG_VFDB_Harmonized.tsv", sep="\t")

# Count samples by data source
sample_counts = df.groupby(["Sample_ID", "Data_source"]).size().unstack(fill_value=0)

print(sample_counts.head())
print(f"Total samples: {len(sample_counts)}")

# Find samples that have only ARG or only VF
only_arg = sample_counts[(sample_counts["ARG"] > 0) & (sample_counts["VF"] == 0)]
only_vf  = sample_counts[(sample_counts["VF"] > 0) & (sample_counts["ARG"] == 0)]

print(f"Samples with only ARG: {len(only_arg)}")
print(f"Samples with only VF: {len(only_vf)}")

# ==========================================================
# ARG–VF Functional Integration Analysis
# ==========================================================
import pandas as pd
import numpy as np
from scipy.stats import spearmanr, entropy

# ---------- LOAD DATA ----------
df = pd.read_csv("Combined_ARG_VFDB_Harmonized.tsv", sep="\t")

# ==========================================================
# COMPUTE SUMMARY METRICS PER SAMPLE
# ==========================================================
summary = df.groupby(["Sample_ID", "Data_source"]).agg(
    Total_TPM=("TPM", "sum"),
    Mechanism_Richness=("Mechanisms", "nunique")
).reset_index()

# Pivot to wide format
summary_wide = summary.pivot(index="Sample_ID", columns="Data_source", values=["Total_TPM", "Mechanism_Richness"]).fillna(0)
summary_wide.columns = ["_".join(col).strip() for col in summary_wide.columns.values]
summary_wide.reset_index(inplace=True)

# ==========================================================
# BALANCE METRICS
# ==========================================================
# ARG–VF TPM ratio (avoid division by zero)
summary_wide["ARG_VF_TPM_ratio"] = np.log2((summary_wide["Total_TPM_ARG"] + 1) / (summary_wide["Total_TPM_VF"] + 1))

# ARG–VF richness ratio
summary_wide["ARG_VF_richness_ratio"] = np.log2((summary_wide["Mechanism_Richness_ARG"] + 1) / (summary_wide["Mechanism_Richness_VF"] + 1))

# ==========================================================
# CORRELATION (global co-selection strength)
# ==========================================================
corr, pval = spearmanr(summary_wide["Total_TPM_ARG"], summary_wide["Total_TPM_VF"])
print(f"\n Global ARG–VF TPM correlation (Spearman): r = {corr:.3f}, p = {pval:.2e}")

# ==========================================================
# ENTROPY-BASED INTEGRATION SCORE
# ==========================================================
# Calculate normalized Shannon entropy for ARG/VF balance per sample
def integration_entropy(row):
    probs = np.array([row["Total_TPM_ARG"], row["Total_TPM_VF"]])
    probs = probs / probs.sum()
    return entropy(probs, base=2)

summary_wide["Integration_Entropy"] = summary_wide.apply(integration_entropy, axis=1)

# ==========================================================
# SAVE SUMMARY TABLE
# ==========================================================
summary_wide.to_csv("ARG_VF_Functional_Integration_Summary.tsv", sep="\t", index=False)

# ==========================================================
# SUMMARY STATS
# ==========================================================
print("\n ARG–VF Functional Integration Summary:")
print(f"Samples analyzed: {len(summary_wide)}")
print(f"Average TPM ratio (ARG/VF): {summary_wide['ARG_VF_TPM_ratio'].mean():.2f}")
print(f"Average richness ratio: {summary_wide['ARG_VF_richness_ratio'].mean():.2f}")
print(f"Mean integration entropy: {summary_wide['Integration_Entropy'].mean():.3f}")
print(" Saved: ARG_VF_Functional_Integration_Summary.tsv")

# ==========================================================
#  Mechanism & Gene Co-occurrence Analysis
# ==========================================================
import pandas as pd
from itertools import combinations

# ---------- LOAD HARMONIZED DATA ----------
df = pd.read_csv("Combined_ARG_VFDB_Harmonized.tsv", sep="\t")

# ==========================================================
# DEFINE CO-OCCURRENCE CONTEXT
# ==========================================================
# You can choose to calculate co-occurrence by 'Sample_ID' or 'Genome'
context = "Sample_ID"   # or 'Genome' if you included that column

# Filter out any non-functional rows
df = df[df["Mechanisms"].notna()]
df = df[df["Mechanisms"] != "Unknown"]

# ==========================================================
# BUILD MECHANISM CO-OCCURRENCE TABLE
# ==========================================================
cooccurrences = []

# For each context (sample or genome), get all mechanism combinations
for ctx_id, group in df.groupby(context):
    mechanisms = group["Mechanisms"].unique().tolist()
    for combo in combinations(sorted(mechanisms), 2):
        cooccurrences.append(combo)

# Convert to dataframe and count frequency
cooc_df = pd.DataFrame(cooccurrences, columns=["Mechanism_A", "Mechanism_B"])
cooc_counts = cooc_df.value_counts().reset_index(name="Cooccurrence_Count")

# Save mechanism co-occurrence table
cooc_counts.to_csv("Mechanism_Cooccurrence_from_Harmonized.tsv", sep="\t", index=False)

print(f" Saved: Mechanism_Cooccurrence_from_Harmonized.tsv ({len(cooc_counts)} pairs)")

# ==========================================================
# BUILD GENE-LEVEL CO-OCCURRENCE TABLE (optional)
# ==========================================================
gene_pairs = []

for ctx_id, group in df.groupby(context):
    genes = group["Gene_ID"].unique().tolist()
    for combo in combinations(sorted(genes), 2):
        gene_pairs.append(combo)

gene_df = pd.DataFrame(gene_pairs, columns=["Gene_A", "Gene_B"])
gene_counts = gene_df.value_counts().reset_index(name="Cooccurrence_Count")

gene_counts.to_csv("Gene_Cooccurrence_from_Harmonized.tsv", sep="\t", index=False)

print(f" Saved: Gene_Cooccurrence_from_Harmonized.tsv ({len(gene_counts)} pairs)")

# ==========================================================
# SUMMARY
# ==========================================================
print("\n Co-occurrence analysis complete!")
print(f"Mechanism pairs: {len(cooc_counts)}")
print(f"Gene pairs: {len(gene_counts)}")
print("Use these files to identify dominant functional and genetic co-occurrence patterns.")